feat(Write): Added the Misaka relay event
Misaka-IoT/misaka-vue pull request #51
Opened 2024-05-02 12:27 UTC by z2bguoguo

增加了接力写作的相关页面，投稿机制，点赞机制，阅读机制和登陆系统的一系列功能

2024-05-02 14:06 UTC, kanadeCN commented
main.scss里相关的大多数新样式宽度需要再大些！！最好直接拉到80%。如果有时间的话可以改掉之后交个新pr，没空的话在这里说一声，合了之后我来改一下（＾ν＾）

2024-05-02 14:10 UTC, kanadeCN commented
@vollowx 以后我大多用这个账号

2024-05-02 19:55 UTC, vollowx commented
router: `MisakaWrite` => `write`?

2024-05-02 20:08 UTC, vollowx requested changes
在手机上看的，没能仔细看功能性的东西，只有可读性审核。

2024-05-02 20:08 UTC, vollowx commented on src/components/MisakaWrite/LoginButton.vue
> +  <MisakaLogin :on="on" @LoginSwich="But"></MisakaLogin>
For better readability and maintainability, change
- `MisakaLogin` to `Login`
- `on` to `visible`
- `But` to `toggle_visibility`

2024-05-02 20:08 UTC, vollowx commented on src/components/MisakaWrite/Upload.vue
> +        this.info = '没有登陆';
未登录

2024-05-02 20:08 UTC, vollowx commented on src/components/MisakaWrite/Upload.vue
> +              this.info = '用户错误';
含义不明

2024-05-02 20:08 UTC, vollowx commented on src/styles/main.scss
> +.Login-on {
不应大写，后同

2024-05-03 14:52 UTC, kanadeCN requested changes

2024-05-04 03:05 UTC, z2bguoguo commented on src/components/MisakaWrite/Upload.vue
> +              this.info = '用户错误';
判断是否提交成功的，因为服务器一些缓存逻辑，太过频繁的提交或者脸黑容易出现错误，以及可能会出现用户异地登陆的情况，网页不会立即同步，有个判断用户是否有权限的判断

2024-05-04 04:54 UTC, vollowx commented on src/components/MisakaWrite/Upload.vue
> +              this.info = '用户错误';
最好还是把错误写详细一点

2024-05-04 04:56 UTC, z2bguoguo commented on src/components/MisakaWrite/Upload.vue
> +              this.info = '用户错误';
好的

2024-05-04 07:28 UTC, kanadeCN commented on src/components/MisakaWrite/Upload.vue
> +              this.info = '用户错误';
第一次用这个批注功能…fork的仓库更改了之后这里会自动同步吗，还是说要重新开pr？

2024-05-04 08:00 UTC, vollowx commented on src/components/MisakaWrite/Upload.vue
> +              this.info = '用户错误';
会。而且对源仓库有写权限的人可以在用github cli切换到pr的分支后直接push到这里。

2024-05-05 07:32 UTC, z2bguoguo commented
> main.scss里相关的大多数新款式宽度需要再大一些！！最好直接拉到80%。如果有时间的话可以改掉之后交个新pr，没空的话在这里说一声，合了之后我来改一下（＾ν＾） @z2bguoguo

因为我的显卡突发恶疾，刚整好就要开学了，抽空修吧

2024-05-19 03:01 UTC, kanadeCN commented
偷偷用学校电脑试了一下，感觉直接加大宽度不太行，会被左边的导航栏遮掉。想了两种方法，一个是把这些阅读框登录框全放在最上层，盖住导航，不过会很乱；还有一种就是媒体查询分开写了，会稍微麻烦一些（）

2024-05-19 06:18 UTC, z2bguoguo commented
> 偷偷用学校电脑试了一下，感觉直接加大宽度不太行，会被左边的导航栏遮掉。想了两种方法，一个就是把这些阅读框登录框全部放在最上层，盖住导航，不过会很乱；还有一种就是媒体查询分开写了，会有点麻烦一些（）

要不弄成显示这些登陆框阅读框啥的时候把导航栏隐藏，导航栏显示的时候隐藏登录框？

2024-05-19 09:07 UTC, kanadeCN commented
> > 偷偷用学校电脑试了一下，感觉直接加大宽度不太行，会被左边的导航栏遮掉。想了两种方法，一个就是把这些阅读框登录框全部放在最上层，盖住导航，不过会很乱；还有一种就是媒体查询分开写了，会有点麻烦一些（）
> 
> 
> 
> 要不弄成显示这些登陆框阅读框啥的时候把导航栏隐藏，导航栏显示的时候隐藏登录框？

也可以

2024-07-16 11:51 UTC, kanadeCN commented
不，不对，这好像没动过手机排版吧![image](https://github.com/user-attachments/assets/0554bf6f-b01b-455a-b8f2-84b9c0cc6447)

2024-07-16 11:52 UTC, z2bguoguo commented
> 不，不对，这好像没过手机排版吧![图像](https://private-user-images.githubusercontent.com/63999920/349071156-0554bf6f-b01b-455a-b8f2-84b9c0cc6447.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzEwMTcsIm5iZiI6MTcyMTEzMDcxNywicGF0aCI6Ii82Mzk5OTkyMC8zNDkwNzExNTYtMDU1NGJmNmYtYjAxYi00NTVhLWI4ZjItODRiOWMwY2M2NDQ3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxMTUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzhhOGIzNzE0MjVmNjM0NDM2YmNmZTJjMzFiNTM3YzQ1MjQ4Y2Y2NjZkN2Y5NmNkMzM0YTE2NWIyMzFmNjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KWlDYY2ZtyfAZ0jGSbN8UhNA8A5yN2_kQoIQuPCKKQ4)

改了那个列表的宽度

2024-07-16 11:54 UTC, kanadeCN commented
> > 不，不对，这好像没过手机排版吧![图像](https://private-user-images.githubusercontent.com/63999920/349071156-0554bf6f-b01b-455a-b8f2-84b9c0cc6447.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzEwMTcsIm5iZiI6MTcyMTEzMDcxNywicGF0aCI6Ii82Mzk5OTkyMC8zNDkwNzExNTYtMDU1NGJmNmYtYjAxYi00NTVhLWI4ZjItODRiOWMwY2M2NDQ3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxMTUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzhhOGIzNzE0MjVmNjM0NDM2YmNmZTJjMzFiNTM3YzQ1MjQ4Y2Y2NjZkN2Y5NmNkMzM0YTE2NWIyMzFmNjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KWlDYY2ZtyfAZ0jGSbN8UhNA8A5yN2_kQoIQuPCKKQ4)
> 
> 
> 
> 改了那个列表的宽度

我这里看还是老样子，不知道是不是我的问题，但是我缓存已经清理过了

2024-07-16 12:02 UTC, z2bguoguo commented
> > > 不对，这好像没过手机排版吧![图像](https://private-user-images.githubusercontent.com/63999920/349071156-0554bf6f-b01b-455a-b8f2-84b9c0cc6447.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzEwMTcsIm5iZiI6MTcyMTEzMDcxNywicGF0aCI6Ii82Mzk5OTkyMC8zNDkwNzExNTYtMDU1NGJmNmYtYjAxYi00NTVhLWI4ZjItODRiOWMwY2M2NDQ3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxMTUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzhhOGIzNzE0MjVmNjM0NDM2YmNmZTJjMzFiNTM3YzQ1MjQ4Y2Y2NjZkN2Y5NmNkMzM0YTE2NWIyMzFmNjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KWlDYY2ZtyfAZ0jGSbN8UhNA8A5yN2_kQoIQuPCKKQ4)
> > 
> > 
> > 改變的寬闊
> 
> 我这里看还是老样子，不知道是不是我的问题，但是我的缓存已经清理过了

我又改了下

2024-07-16 12:06 UTC, kanadeCN commented
> > > > 不对，这好像没过手机排版吧![图像](https://private-user-images.githubusercontent.com/63999920/349071156-0554bf6f-b01b-455a-b8f2-84b9c0cc6447.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzEwMTcsIm5iZiI6MTcyMTEzMDcxNywicGF0aCI6Ii82Mzk5OTkyMC8zNDkwNzExNTYtMDU1NGJmNmYtYjAxYi00NTVhLWI4ZjItODRiOWMwY2M2NDQ3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxMTUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzhhOGIzNzE0MjVmNjM0NDM2YmNmZTJjMzFiNTM3YzQ1MjQ4Y2Y2NjZkN2Y5NmNkMzM0YTE2NWIyMzFmNjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KWlDYY2ZtyfAZ0jGSbN8UhNA8A5yN2_kQoIQuPCKKQ4)
> 
> > > 
> 
> > > 
> 
> > > 改變的寬闊
> 
> > 
> 
> > 我这里看还是老样子，不知道是不是我的问题，但是我的缓存已经清理过了
> 
> 
> 
> 我又改了下

85%

2024-07-16 12:10 UTC, z2bguoguo commented
![msedge_ESRdEgiz94](https://github.com/user-attachments/assets/cae6ab7f-de49-499e-be23-1d59a3e930da)
还有啥别的不优雅问题吗

2024-07-16 12:18 UTC, merged